### Importing Warnings

In [1]:
import warnings
warnings.filterwarnings('ignore')


### Importing Packages




In [2]:
import pandas as pd
import numpy as np

### Importing Dataset Using Pandas

In [3]:
data=pd.read_csv('heart.csv')

### Know dataset Structure

In [4]:
data.shape

(303, 14)

### Know columns


In [5]:
data.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output'],
      dtype='object')

### Let's see all rows 

In [6]:
pd.options.display.max_rows=5000
data.head(303)

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
5     57    1   0     140   192    0        1       148     0      0.4    1   
6     56    0   1     140   294    0        0       153     0      1.3    1   
7     44    1   1     120   263    0        1       173     0      0.0    2   
8     52    1   2     172   199    1        1       162     0      0.5    2   
9     57    1   2     150   168    0        1       174     0      1.6    2   
10    54    1   0     140   239    0        1       160     0      1.2    2   
11    48    0   2     130   275    0        1       139     0      0.2    2   
12    49    1   1     130   266    0        1       171     0      0.6    2   
13    64    1   3     110   211    0        0       144     1      1.8    1   
14    58    0   3     150   283    1        0       162     0      1.0    2   
15    50    0   2     120   219    0        1       158     0      1.6    1   
16    58    0   2     120   340    0        1       172     0      0.0    2   
17    66    0   3     150   226    0        1       114     0      2.6    0   
18    43    1   0     150   247    0        1       171     0      1.5    2   
19    69    0   3     140   239    0        1       151     0      1.8    2   
20    59    1   0     135   234    0        1       161     0      0.5    1   
21    44    1   2     130   233    0        1       179     1      0.4    2   
22    42    1   0     140   226    0        1       178     0      0.0    2   
23    61    1   2     150   243    1        1       137     1      1.0    1   
24    40    1   3     140   199    0        1       178     1      1.4    2   
25    71    0   1     160   302    0        1       162     0      0.4    2   
26    59    1   2     150   212    1        1       157     0      1.6    2   
27    51    1   2     110   175    0        1       123     0      0.6    2   
28    65    0   2     140   417    1        0       157     0      0.8    2   
29    53    1   2     130   197    1        0       152     0      1.2    0   
30    41    0   1     105   198    0        1       168     0      0.0    2   
31    65    1   0     120   177    0        1       140     0      0.4    2   
32    44    1   1     130   219    0        0       188     0      0.0    2   
33    54    1   2     125   273    0        0       152     0      0.5    0   
34    51    1   3     125   213    0        0       125     1      1.4    2   
35    46    0   2     142   177    0        0       160     1      1.4    0   
36    54    0   2     135   304    1        1       170     0      0.0    2   
37    54    1   2     150   232    0        0       165     0      1.6    2   
38    65    0   2     155   269    0        1       148     0      0.8    2   
39    65    0   2     160   360    0        0       151     0      0.8    2   
40    51    0   2     140   308    0        0       142     0      1.5    2   
41    48    1   1     130   245    0        0       180     0      0.2    1   
42    45    1   0     104   208    0        0       148     1      3.0    1   
43    53    0   0     130   264    0        0       143     0      0.4    1   
44    39    1   2     140   321    0        0       182     0      0.0    2   
45    52    1   1     120   325    0        1       172     0      0.2    2   
46    44    1   2     140   235    0        0       180     0      0.0    2   
47    47    1   2     138   257    0        0       156     0      0.0    2   
48    53    0   2     128   216    0        0       115     0      0.0    2   
49    53    0   0     138   234    0        0       160

### Information regarding columns


In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trtbps    303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalachh  303 non-null    int64  
 8   exng      303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64  
 11  caa       303 non-null    int64  
 12  thall     303 non-null    int64  
 13  output    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


### Let's Check Unique Values

#### AGE

In [8]:
data['age'].unique()

array([63, 37, 41, 56, 57, 44, 52, 54, 48, 49, 64, 58, 50, 66, 43, 69, 59,
       42, 61, 40, 71, 51, 65, 53, 46, 45, 39, 47, 62, 34, 35, 29, 55, 60,
       67, 68, 74, 76, 70, 38, 77], dtype=int64)

#### SEX

In [9]:
data['sex'].unique()   ## 0 is Female and 1 is Male

array([1, 0], dtype=int64)

### Chest Pain Range

In [11]:
data['cp'].unique()

array([3, 2, 1, 0], dtype=int64)

### Resting Blood Pressure

In [14]:
data['trtbps'].unique()

array([145, 130, 120, 140, 172, 150, 110, 135, 160, 105, 125, 142, 155,
       104, 138, 128, 108, 134, 122, 115, 118, 100, 124,  94, 112, 102,
       152, 101, 132, 148, 178, 129, 180, 136, 126, 106, 156, 170, 146,
       117, 200, 165, 174, 192, 144, 123, 154, 114, 164], dtype=int64)

### Cholesterol

In [15]:
data['chol'].unique()

array([233, 250, 204, 236, 354, 192, 294, 263, 199, 168, 239, 275, 266,
       211, 283, 219, 340, 226, 247, 234, 243, 302, 212, 175, 417, 197,
       198, 177, 273, 213, 304, 232, 269, 360, 308, 245, 208, 264, 321,
       325, 235, 257, 216, 256, 231, 141, 252, 201, 222, 260, 182, 303,
       265, 309, 186, 203, 183, 220, 209, 258, 227, 261, 221, 205, 240,
       318, 298, 564, 277, 214, 248, 255, 207, 223, 288, 160, 394, 315,
       246, 244, 270, 195, 196, 254, 126, 313, 262, 215, 193, 271, 268,
       267, 210, 295, 306, 178, 242, 180, 228, 149, 278, 253, 342, 157,
       286, 229, 284, 224, 206, 167, 230, 335, 276, 353, 225, 330, 290,
       172, 305, 188, 282, 185, 326, 274, 164, 307, 249, 341, 407, 217,
       174, 281, 289, 322, 299, 300, 293, 184, 409, 259, 200, 327, 237,
       218, 319, 166, 311, 169, 187, 176, 241, 131], dtype=int64)

### fbs

In [16]:
data['fbs'].unique()

array([1, 0], dtype=int64)

### Resting ECG

In [17]:
data['restecg'].unique()

array([0, 1, 2], dtype=int64)

### Maximum Heart Rate Achieved

In [18]:
data['thalachh'].unique()

array([150, 187, 172, 178, 163, 148, 153, 173, 162, 174, 160, 139, 171,
       144, 158, 114, 151, 161, 179, 137, 157, 123, 152, 168, 140, 188,
       125, 170, 165, 142, 180, 143, 182, 156, 115, 149, 146, 175, 186,
       185, 159, 130, 190, 132, 147, 154, 202, 166, 164, 184, 122, 169,
       138, 111, 145, 194, 131, 133, 155, 167, 192, 121,  96, 126, 105,
       181, 116, 108, 129, 120, 112, 128, 109, 113,  99, 177, 141, 136,
        97, 127, 103, 124,  88, 195, 106,  95, 117,  71, 118, 134,  90],
      dtype=int64)

### exng

In [19]:
data['exng'].unique()

array([0, 1], dtype=int64)

### oldpeak

In [20]:
data['oldpeak'].unique()

array([2.3, 3.5, 1.4, 0.8, 0.6, 0.4, 1.3, 0. , 0.5, 1.6, 1.2, 0.2, 1.8,
       1. , 2.6, 1.5, 3. , 2.4, 0.1, 1.9, 4.2, 1.1, 2. , 0.7, 0.3, 0.9,
       3.6, 3.1, 3.2, 2.5, 2.2, 2.8, 3.4, 6.2, 4. , 5.6, 2.9, 2.1, 3.8,
       4.4])

### slp

In [21]:
data['slp'].unique()

array([0, 2, 1], dtype=int64)

### caa

In [22]:
data['caa'].unique()

array([0, 2, 1, 3, 4], dtype=int64)

### thall

In [23]:
data['thall'].unique()

array([1, 2, 3, 0], dtype=int64)

### output

In [24]:
data['output'].unique()  ## Less Chance of Heart Attack
                         ## More Chance of Heart attack

array([1, 0], dtype=int64)

### Let's See Mean Mode Median And Quartiles Of Each Column

In [25]:
data.describe()

age         sex          cp      trtbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg    thalachh        exng     oldpeak         slp         caa  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

            thall      output  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

### Let's See For Duplicates

In [26]:
data.duplicated().sum()   ### There Were No Duplicates

1

### Let's See Is There Any Null Values

In [27]:
data.isnull().sum()       #### There Were No Null Values

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64